spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/gss_event_db?useSSL=false
    username: root
    password: root123
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
    port: 8282
    
server.servlet.session.timeout: 600000ms
        
        